name: Tests

on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches:
      - "*"
env:
  mumbai_rpc: ${{ vars.POLYGON_MUMBAI_RPC_URL }}

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test hardhat-mocha on Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    steps:
      - name: log var
        run: |
          echo "repository variable : $mumbai_rpc"
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
      - name: Install
        run: yarn --frozen-lockfile
      - name: Compile
        run: yarn compile
      - name: Run tests
        run: yarn test
